# Generated by Django 3.2.3 on 2021-06-12 05:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('d', models.DateTimeField(auto_now=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
    ]
